name: galaxyapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  cloud_firestore: '^0.7.0'
  firebase_auth: '^0.5.5'
  simple_coverflow: '^0.0.6'
  transparent_image: '^0.1.0'
  sensors: '^0.3.5'
  audioplayers: '^0.7.8'
  path_provider: '^0.4.1'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/background.mp3
    - assets/removed.mp3
  uses-material-design: true
